version: "3.8"

services:
  zookeeper:
    container_name: hello-zookeeper
    image: docker.io/zookeeper:latest
    ports:
      - "2181:2181"
    volumes:
      - "zookeeper_data:/data"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    container_name: hello-kafka
    image: docker.io/bitnami/kafka:latest
    ports:
      - "9092:9092"
    volumes:
      - type: volume
        source: zookeeper_data
        target: "/data"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
    depends_on:
      - zookeeper
volumes:
  zookeeper_data:
      driver: local
  kafka_data:
      driver: local